# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\FileBox\Gobang\GobangGame\Board\resource\board.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1200, 947)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(1200, 947))
        Form.setMaximumSize(QtCore.QSize(1200, 947))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/main/map.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 2, 2)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.map = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.map.sizePolicy().hasHeightForWidth())
        self.map.setSizePolicy(sizePolicy)
        self.map.setMinimumSize(QtCore.QSize(955, 947))
        self.map.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.map.setStyleSheet("QWidget {\n"
"    background: rgb(255, 255, 191);\n"
"    border: 3px solid rgb(172, 172, 172);\n"
"}")
        self.map.setObjectName("map")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.map)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout.addWidget(self.map)
        self.widget_2 = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(220, 0))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setContentsMargins(2, 30, 2, 5)
        self.verticalLayout_2.setSpacing(25)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lcd_timer = QtWidgets.QLCDNumber(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcd_timer.sizePolicy().hasHeightForWidth())
        self.lcd_timer.setSizePolicy(sizePolicy)
        self.lcd_timer.setMinimumSize(QtCore.QSize(0, 40))
        self.lcd_timer.setStyleSheet("QLCDNumber {\n"
"    border: none;\n"
"}")
        self.lcd_timer.setFrameShape(QtWidgets.QFrame.Box)
        self.lcd_timer.setDigitCount(8)
        self.lcd_timer.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_timer.setObjectName("lcd_timer")
        self.verticalLayout_2.addWidget(self.lcd_timer)
        self.label = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.rbt_black = QtWidgets.QRadioButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbt_black.sizePolicy().hasHeightForWidth())
        self.rbt_black.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.rbt_black.setFont(font)
        self.rbt_black.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rbt_black.setChecked(True)
        self.rbt_black.setObjectName("rbt_black")
        self.horizontalLayout_2.addWidget(self.rbt_black)
        self.rbt_white = QtWidgets.QRadioButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbt_white.sizePolicy().hasHeightForWidth())
        self.rbt_white.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.rbt_white.setFont(font)
        self.rbt_white.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rbt_white.setObjectName("rbt_white")
        self.horizontalLayout_2.addWidget(self.rbt_white)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pbt_start = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbt_start.sizePolicy().hasHeightForWidth())
        self.pbt_start.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pbt_start.setFont(font)
        self.pbt_start.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pbt_start.setStyleSheet("QPushButton {\n"
"    border-style:none;\n"
"    padding:10px;\n"
"    border-radius:15px;\n"
"    color:#FFFFFF;\n"
"    background:#34495E;\n"
"}\n"
"QPushButton:hover {\n"
"    color:#4E6D8C;\n"
"    background:#e5e5e5;\n"
"    border:2px solid #34495E;\n"
"}\n"
"QPushButton:pressed {\n"
"    color:#000000;\n"
"    background:#B8C6D1;\n"
"}\n"
"QPushButton:disabled {\n"
"    background: rgb(119, 118, 127);\n"
"}\n"
"")
        self.pbt_start.setObjectName("pbt_start")
        self.horizontalLayout_4.addWidget(self.pbt_start)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pbt_swap = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbt_swap.sizePolicy().hasHeightForWidth())
        self.pbt_swap.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pbt_swap.setFont(font)
        self.pbt_swap.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pbt_swap.setStyleSheet("QPushButton {\n"
"    border-style:none;\n"
"    padding:10px;\n"
"    border-radius:15px;\n"
"    color:#FFFFFF;\n"
"    background:#34495E;\n"
"}\n"
"QPushButton:hover {\n"
"    color:#4E6D8C;\n"
"    background:#e5e5e5;\n"
"    border:2px solid #34495E;\n"
"}\n"
"QPushButton:pressed {\n"
"    color:#000000;\n"
"    background:#B8C6D1;\n"
"}\n"
"QPushButton:disabled {\n"
"    background: rgb(119, 118, 127);\n"
"}\n"
"")
        self.pbt_swap.setObjectName("pbt_swap")
        self.horizontalLayout_3.addWidget(self.pbt_swap)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pbt_save = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbt_save.sizePolicy().hasHeightForWidth())
        self.pbt_save.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pbt_save.setFont(font)
        self.pbt_save.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pbt_save.setStyleSheet("QPushButton {\n"
"    border-style:none;\n"
"    padding:10px;\n"
"    border-radius:15px;\n"
"    color:#FFFFFF;\n"
"    background:#34495E;\n"
"}\n"
"QPushButton:hover {\n"
"    color:#4E6D8C;\n"
"    background:#e5e5e5;\n"
"    border:2px solid #34495E;\n"
"}\n"
"QPushButton:pressed {\n"
"    color:#000000;\n"
"    background:#B8C6D1;\n"
"}\n"
"QPushButton:disabled {\n"
"    background: rgb(119, 118, 127);\n"
"}\n"
"")
        self.pbt_save.setObjectName("pbt_save")
        self.horizontalLayout_6.addWidget(self.pbt_save)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        spacerItem = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, -1, 5, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tb_logs = QtWidgets.QTextBrowser(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tb_logs.sizePolicy().hasHeightForWidth())
        self.tb_logs.setSizePolicy(sizePolicy)
        self.tb_logs.setMinimumSize(QtCore.QSize(0, 300))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.tb_logs.setFont(font)
        self.tb_logs.setStyleSheet("QTextBrowser {\n"
"    border: 3px solid rgb(172, 172, 172);\n"
"}")
        self.tb_logs.setObjectName("tb_logs")
        self.verticalLayout_3.addWidget(self.tb_logs)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.horizontalLayout.addWidget(self.widget_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "本机AI 棋子:"))
        self.rbt_black.setToolTip(_translate("Form", "AI为黑棋"))
        self.rbt_black.setText(_translate("Form", "黑棋"))
        self.rbt_white.setToolTip(_translate("Form", "AI为白棋"))
        self.rbt_white.setText(_translate("Form", "白棋"))
        self.pbt_start.setToolTip(_translate("Form", "开始游戏"))
        self.pbt_start.setText(_translate("Form", "先手开局"))
        self.pbt_swap.setToolTip(_translate("Form", "三手交换"))
        self.pbt_swap.setText(_translate("Form", "三手交换"))
        self.pbt_save.setToolTip(_translate("Form", "保存当前棋盘"))
        self.pbt_save.setText(_translate("Form", "保存棋盘"))


import resource.icon_rc
